function [alias, langName] = getPrismAlias(filePath)
% GETPRISMALIAS Map a file path, file name, or extension to its 
% corresponding Prism.js class alias & language name.
%
% Usage:
%   [alias, langName] = getPrismAlias('C:/projects/app.component.ts')
%   [alias, langName] = getPrismAlias('.gitignore')
%   [alias, langName] = getPrismAlias('script.py')
%   [alias, langName] = getPrismAlias('wasm')

    % Clean input (convert string objects to char array and strip whitespace)
    filePath = char(filePath);
    filePath = strtrim(filePath);

    % Extract filename and extension
    [~, name, ext] = fileparts(filePath);

    % Handle special dotfiles (e.g., '.gitignore' where fileparts gives name='.gitignore', ext='')
    if isempty(ext) && startsWith(name, '.')
        ext = name(2:end); % use 'gitignore'
    elseif startsWith(ext, '.')
        ext = ext(2:end); % strip leading dot from '.ts'
    elseif isempty(ext)
        ext = name; % fallback if user passed 'wasm' directly without dot
    end

    ext = lower(ext);

    persistent mapDatabase;
    if isempty(mapDatabase)
        % Define full Prism language database: Extension -> {Alias, Language Name}
        mapDatabase = containers.Map(...
            { ...
                'html', 'htm', 'xml', 'svg', 'mathml', 'ssml', 'atom', 'rss', ...
                'css', 'clike', 'js', 'javascript', 'abap', 'abnf', 'actionscript', ...
                'ada', 'agda', 'al', 'antlr4', 'g4', 'apacheconf', 'apex', 'apl', ...
                'applescript', 'aql', 'ino', 'arduino', 'arff', 'armasm', 'arm-asm', ...
                'art', 'arturo', 'adoc', 'asciidoc', 'aspnet', 'asm6502', 'asmatmel', ...
                'autohotkey', 'autoit', 'avs', 'avisynth', 'avro-idl', 'avdl', 'awk', 'gawk', ...
                'sh', 'bash', 'shell', 'basic', 'bat', 'batch', 'bbcode', 'shortcode', 'bbj', ...
                'bicep', 'birb', 'bison', 'bnf', 'rbnf', 'bqn', 'brainfuck', 'brightscript', ...
                'bro', 'bsl', 'oscript', 'c', 'cs', 'csharp', 'dotnet', 'cpp', 'cc', 'cxx', ...
                'cfc', 'cfscript', 'chaiscript', 'cil', 'cilkc', 'cilk-c', 'cilkcpp', 'cilk-cpp', 'cilk', ...
                'clj', 'clojure', 'cmake', 'cob', 'cobol', 'coffee', 'coffeescript', 'conc', 'concurnas', ...
                'csp', 'cooklang', 'v', 'coq', 'cr', 'crystal', 'css-extras', 'csv', 'cue', ...
                'cyp', 'cypher', 'd', 'dart', 'dw', 'dataweave', 'dax', 'dhall', 'diff', ...
                'jinja', 'jinja2', 'django', 'zone', 'dns-zone-file', 'dns-zone', 'docker', 'dockerfile', ...
                'dot', 'gv', 'ebnf', 'editorconfig', 'eiffel', 'ejs', 'eta', 'ex', 'exs', 'elixir', ...
                'elm', 'etlua', 'erb', 'erl', 'erlang', 'xlsx', 'xls', 'excel-formula', 'fs', 'fsharp', ...
                'factor', 'false', 'firestore-security-rules', 'flow', 'f', 'f90', 'fortran', 'ftl', ...
                'gml', 'gamemakerlanguage', 'gap', 'gcode', 'gd', 'gdscript', 'ged', 'gedcom', ...
                'po', 'gettext', 'feature', 'gherkin', 'git', 'glsl', 'gn', 'gni', 'ld', 'linker-script', ...
                'go', 'go-mod', 'go-module', 'gradle', 'graphql', 'gql', 'groovy', 'haml', 'hbs', ...
                'handlebars', 'mustache', 'hs', 'haskell', 'hx', 'haxe', 'hcl', 'tf', 'hlsl', ...
                'hoon', 'http', 'hpkp', 'hsts', 'ichigojam', 'icon', 'icu-message-format', 'idr', 'idris', ...
                'ignore', 'gitignore', 'hgignore', 'npmignore', 'ni', 'inform7', 'ini', 'cfg', 'io', ...
                'j', 'java', 'javadoc', 'javadoclike', 'javastacktrace', 'jexl', 'jolie', 'jq', ...
                'jsdoc', 'js-extras', 'json', 'webmanifest', 'json5', 'jsonp', 'jsstacktrace', ...
                'js-templates', 'jl', 'julia', 'keepalived', 'keyman', 'kt', 'kts', 'kotlin', ...
                'kum', 'kumir', 'kusto', 'tex', 'latex', 'context', 'latte', 'less', 'ly', 'lilypond', ...
                'liquid', 'el', 'lisp', 'emacs', 'elisp', 'emacs-lisp', 'ls', 'livescript', 'llvm', ...
                'log', 'lol', 'lolcode', 'lua', 'magma', 'mk', 'makefile', 'md', 'markdown', ...
                'markup-templating', 'mata', 'm', 'matlab', 'maxscript', 'mel', 'mermaid', 'metafont', ...
                'mizar', 'mongodb', 'monkey', 'moon', 'moonscript', 'n1ql', 'n4js', 'n4jsd', ...
                'nand2tetris-hdl', 'nani', 'naniscript', 'asm', 'nasm', 'neon', 'nevod', 'nginx', ...
                'nim', 'nix', 'nsi', 'nsis', 'm', 'mm', 'objc', 'objectivec', 'ml', 'mli', 'ocaml', ...
                'odin', 'cl', 'opencl', 'qasm', 'openqasm', 'oz', 'gp', 'parigp', 'parser', ...
                'pas', 'pascal', 'objectpascal', 'pascaligo', 'psl', 'px', 'pcaxis', 'pcode', ...
                'peoplecode', 'pl', 'pm', 'perl', 'php', 'phpdoc', 'php-extras', 'puml', 'plantuml', ...
                'plant-uml', 'plsql', 'pq', 'mscript', 'powerquery', 'ps1', 'psm1', 'powershell', ...
                'pde', 'processing', 'prolog', 'promql', 'properties', 'proto', 'protobuf', 'pug', ...
                'pp', 'puppet', 'pure', 'pb', 'purebasic', 'pbfasm', 'purs', 'purescript', ...
                'py', 'python', 'qs', 'qsharp', 'q', 'qml', 'qore', 'r', 'rkt', 'racket', ...
                'cshtml', 'razor', 'jsx', 'tsx', 're', 'reason', 'regex', 'rego', 'rpy', 'renpy', ...
                'res', 'rescript', 'rst', 'rest', 'rip', 'roboconf', 'robot', 'robotframework', ...
                'rb', 'ruby', 'rs', 'rust', 'sas', 'sass', 'scss', 'scala', 'scm', 'scheme', ...
                'sh-session', 'shell-session', 'shellsession', 'smali', 'st', 'smalltalk', ...
                'smarty', 'sml', 'smlnj', 'sol', 'solidity', 'sln', 'solution-file', 'soy', ...
                'rq', 'sparql', 'splunk-spl', 'sqf', 'sql', 'nut', 'squirrel', 'stan', ...
                'ado', 'stata', 'iecst', 'styl', 'stylus', 'sclang', 'supercollider', ...
                'swift', 'systemd', 't4-templating', 't4', 't4-cs', 't4-vb', 'tap', 'tcl', ...
                'tt2', 'textile', 'toml', 'trickle', 'troy', 'tremor', 'trig', 'turtle', ...
                'twig', 'ts', 'typescript', 'tsconfig', 'typoscript', 'uc', 'uscript', 'unrealscript', ...
                'uorazor', 'uri', 'url', 'v', 'vala', 'vbnet', 'vm', 'velocity', 'v', 'sv', 'verilog', ...
                'vhd', 'vhdl', 'vim', 'vb', 'vba', 'visual-basic', 'warpscript', 'wasm', 'webassembly', ...
                'webidl', 'web-idl', 'wgsl', 'wiki', 'wl', 'nb', 'wolfram', 'mathematica', 'wren', ...
                'xeora', 'xeoracube', 'xml-doc', 'xojo', 'xq', 'xquery', 'yml', 'yaml', 'yang', 'zig' ...
            }, ...
            { ...
                {'markup', 'Markup'}, {'markup', 'Markup'}, {'markup', 'Markup'}, {'markup', 'Markup'}, {'markup', 'Markup'}, {'markup', 'Markup'}, {'markup', 'Markup'}, {'markup', 'Markup'}, ...
                {'css', 'CSS'}, {'clike', 'C-like'}, {'javascript', 'JavaScript'}, {'javascript', 'JavaScript'}, {'abap', 'ABAP'}, {'abnf', 'ABNF'}, {'actionscript', 'ActionScript'}, ...
                {'ada', 'Ada'}, {'agda', 'Agda'}, {'al', 'AL'}, {'antlr4', 'ANTLR4'}, {'antlr4', 'ANTLR4'}, {'apacheconf', 'Apache Configuration'}, {'apex', 'Apex'}, {'apl', 'APL'}, ...
                {'applescript', 'AppleScript'}, {'aql', 'AQL'}, {'arduino', 'Arduino'}, {'arduino', 'Arduino'}, {'arff', 'ARFF'}, {'armasm', 'ARM Assembly'}, {'armasm', 'ARM Assembly'}, ...
                {'arturo', 'Arturo'}, {'arturo', 'Arturo'}, {'asciidoc', 'AsciiDoc'}, {'asciidoc', 'AsciiDoc'}, {'aspnet', 'ASP.NET (C#)'}, {'asm6502', '6502 Assembly'}, {'asmatmel', 'Atmel AVR Assembly'}, ...
                {'autohotkey', 'AutoHotkey'}, {'autoit', 'AutoIt'}, {'avisynth', 'AviSynth'}, {'avisynth', 'AviSynth'}, {'avro-idl', 'Avro IDL'}, {'avro-idl', 'Avro IDL'}, {'awk', 'AWK'}, {'awk', 'AWK'}, ...
                {'bash', 'Bash'}, {'bash', 'Bash'}, {'bash', 'Bash'}, {'basic', 'BASIC'}, {'batch', 'Batch'}, {'batch', 'Batch'}, {'bbcode', 'BBcode'}, {'bbcode', 'BBcode'}, {'bbj', 'BBj'}, ...
                {'bicep', 'Bicep'}, {'birb', 'Birb'}, {'bison', 'Bison'}, {'bnf', 'BNF'}, {'bnf', 'BNF'}, {'bqn', 'BQN'}, {'brainfuck', 'Brainfuck'}, {'brightscript', 'BrightScript'}, ...
                {'bro', 'Bro'}, {'bsl', 'BSL (1C:Enterprise)'}, {'bsl', 'BSL (1C:Enterprise)'}, {'c', 'C'}, {'csharp', 'C#'}, {'csharp', 'C#'}, {'csharp', 'C#'}, {'cpp', 'C++'}, {'cpp', 'C++'}, {'cpp', 'C++'}, ...
                {'cfscript', 'CFScript'}, {'cfscript', 'CFScript'}, {'chaiscript', 'ChaiScript'}, {'cil', 'CIL'}, {'cilkc', 'Cilk/C'}, {'cilkc', 'Cilk/C'}, {'cilkcpp', 'Cilk/C++'}, {'cilkcpp', 'Cilk/C++'}, {'cilkcpp', 'Cilk/C++'}, ...
                {'clojure', 'Clojure'}, {'clojure', 'Clojure'}, {'cmake', 'CMake'}, {'cobol', 'COBOL'}, {'cobol', 'COBOL'}, {'coffeescript', 'CoffeeScript'}, {'coffeescript', 'CoffeeScript'}, {'concurnas', 'Concurnas'}, {'concurnas', 'Concurnas'}, ...
                {'csp', 'Content-Security-Policy'}, {'cooklang', 'Cooklang'}, {'coq', 'Coq'}, {'coq', 'Coq'}, {'crystal', 'Crystal'}, {'crystal', 'Crystal'}, {'css-extras', 'CSS Extras'}, {'csv', 'CSV'}, {'cue', 'CUE'}, ...
                {'cypher', 'Cypher'}, {'cypher', 'Cypher'}, {'d', 'D'}, {'dart', 'Dart'}, {'dataweave', 'DataWeave'}, {'dataweave', 'DataWeave'}, {'dax', 'DAX'}, {'dhall', 'Dhall'}, {'diff', 'Diff'}, ...
                {'django', 'Django/Jinja2'}, {'django', 'Django/Jinja2'}, {'django', 'Django/Jinja2'}, {'dns-zone-file', 'DNS zone file'}, {'dns-zone-file', 'DNS zone file'}, {'dns-zone-file', 'DNS zone file'}, {'docker', 'Docker'}, {'docker', 'Docker'}, ...
                {'dot', 'DOT (Graphviz)'}, {'dot', 'DOT (Graphviz)'}, {'ebnf', 'EBNF'}, {'editorconfig', 'EditorConfig'}, {'eiffel', 'Eiffel'}, {'ejs', 'EJS'}, {'ejs', 'EJS'}, {'elixir', 'Elixir'}, {'elixir', 'Elixir'}, {'elixir', 'Elixir'}, ...
                {'elm', 'Elm'}, {'etlua', 'Embedded Lua templating'}, {'erb', 'ERB'}, {'erlang', 'Erlang'}, {'erlang', 'Erlang'}, {'excel-formula', 'Excel Formula'}, {'excel-formula', 'Excel Formula'}, {'excel-formula', 'Excel Formula'}, {'fsharp', 'F#'}, {'fsharp', 'F#'}, ...
                {'factor', 'Factor'}, {'false', 'False'}, {'firestore-security-rules', 'Firestore security rules'}, {'flow', 'Flow'}, {'fortran', 'Fortran'}, {'fortran', 'Fortran'}, {'fortran', 'Fortran'}, {'ftl', 'FreeMarker Template Language'}, ...
                {'gml', 'GameMaker Language'}, {'gml', 'GameMaker Language'}, {'gap', 'GAP (CAS)'}, {'gcode', 'G-code'}, {'gdscript', 'GDScript'}, {'gdscript', 'GDScript'}, {'gedcom', 'GEDCOM'}, {'gedcom', 'GEDCOM'}, ...
                {'gettext', 'gettext'}, {'gettext', 'gettext'}, {'gherkin', 'Gherkin'}, {'gherkin', 'Gherkin'}, {'git', 'Git'}, {'glsl', 'GLSL'}, {'gn', 'GN'}, {'gn', 'GN'}, {'linker-script', 'GNU Linker Script'}, {'linker-script', 'GNU Linker Script'}, ...
                {'go', 'Go'}, {'go-module', 'Go module'}, {'go-module', 'Go module'}, {'gradle', 'Gradle'}, {'graphql', 'GraphQL'}, {'graphql', 'GraphQL'}, {'groovy', 'Groovy'}, {'haml', 'Haml'}, {'handlebars', 'Handlebars'}, ...
                {'handlebars', 'Handlebars'}, {'handlebars', 'Handlebars'}, {'haskell', 'Haskell'}, {'haskell', 'Haskell'}, {'haxe', 'Haxe'}, {'haxe', 'Haxe'}, {'hcl', 'HCL'}, {'hcl', 'HCL'}, {'hlsl', 'HLSL'}, ...
                {'hoon', 'Hoon'}, {'http', 'HTTP'}, {'hpkp', 'HTTP Public-Key-Pins'}, {'hsts', 'HTTP Strict-Transport-Security'}, {'ichigojam', 'IchigoJam'}, {'icon', 'Icon'}, {'icu-message-format', 'ICU Message Format'}, {'idris', 'Idris'}, {'idris', 'Idris'}, ...
                {'ignore', '.ignore'}, {'ignore', '.ignore'}, {'ignore', '.ignore'}, {'ignore', '.ignore'}, {'inform7', 'Inform 7'}, {'inform7', 'Inform 7'}, {'ini', 'Ini'}, {'ini', 'Ini'}, {'io', 'Io'}, ...
                {'j', 'J'}, {'java', 'Java'}, {'javadoc', 'JavaDoc'}, {'javadoclike', 'JavaDoc-like'}, {'javastacktrace', 'Java stack trace'}, {'jexl', 'Jexl'}, {'jolie', 'Jolie'}, {'jq', 'JQ'}, ...
                {'jsdoc', 'JSDoc'}, {'js-extras', 'JS Extras'}, {'json', 'JSON'}, {'json', 'JSON'}, {'json5', 'JSON5'}, {'jsonp', 'JSONP'}, {'jsstacktrace', 'JS stack trace'}, ...
                {'js-templates', 'JS Templates'}, {'julia', 'Julia'}, {'julia', 'Julia'}, {'keepalived', 'Keepalived Configure'}, {'keyman', 'Keyman'}, {'kotlin', 'Kotlin'}, {'kotlin', 'Kotlin'}, {'kotlin', 'Kotlin'}, ...
                {'kumir', 'KuMir (КуМир)'}, {'kumir', 'KuMir (КуМир)'}, {'kusto', 'Kusto'}, {'latex', 'LaTeX'}, {'latex', 'LaTeX'}, {'latex', 'LaTeX'}, {'latte', 'Latte'}, {'less', 'Less'}, {'lilypond', 'LilyPond'}, {'lilypond', 'LilyPond'}, ...
                {'liquid', 'Liquid'}, {'lisp', 'Lisp'}, {'lisp', 'Lisp'}, {'lisp', 'Lisp'}, {'lisp', 'Lisp'}, {'lisp', 'Lisp'}, {'livescript', 'LiveScript'}, {'livescript', 'LiveScript'}, {'llvm', 'LLVM IR'}, ...
                {'log', 'Log file'}, {'lolcode', 'LOLCODE'}, {'lolcode', 'LOLCODE'}, {'lua', 'Lua'}, {'magma', 'Magma (CAS)'}, {'makefile', 'Makefile'}, {'makefile', 'Makefile'}, {'markdown', 'Markdown'}, {'markdown', 'Markdown'}, ...
                {'markup-templating', 'Markup templating'}, {'mata', 'Mata'}, {'matlab', 'MATLAB'}, {'matlab', 'MATLAB'}, {'maxscript', 'MAXScript'}, {'mel', 'MEL'}, {'mermaid', 'Mermaid'}, {'metafont', 'METAFONT'}, ...
                {'mizar', 'Mizar'}, {'mongodb', 'MongoDB'}, {'monkey', 'Monkey'}, {'moonscript', 'MoonScript'}, {'moonscript', 'MoonScript'}, {'n1ql', 'N1QL'}, {'n4js', 'N4JS'}, {'n4js', 'N4JS'}, ...
                {'nand2tetris-hdl', 'Nand To Tetris HDL'}, {'naniscript', 'Naninovel Script'}, {'naniscript', 'Naninovel Script'}, {'nasm', 'NASM'}, {'nasm', 'NASM'}, {'neon', 'NEON'}, {'nevod', 'Nevod'}, {'nginx', 'nginx'}, ...
                {'nim', 'Nim'}, {'nix', 'Nix'}, {'nsis', 'NSIS'}, {'nsis', 'NSIS'}, {'objectivec', 'Objective-C'}, {'objectivec', 'Objective-C'}, {'objectivec', 'Objective-C'}, {'objectivec', 'Objective-C'}, {'ocaml', 'OCaml'}, {'ocaml', 'OCaml'}, {'ocaml', 'OCaml'}, ...
                {'odin', 'Odin'}, {'opencl', 'OpenCL'}, {'opencl', 'OpenCL'}, {'openqasm', 'OpenQasm'}, {'openqasm', 'OpenQasm'}, {'oz', 'Oz'}, {'parigp', 'PARI/GP'}, {'parigp', 'PARI/GP'}, {'parser', 'Parser'}, ...
                {'pascal', 'Pascal'}, {'pascal', 'Pascal'}, {'pascal', 'Pascal'}, {'pascaligo', 'Pascaligo'}, {'psl', 'PATROL Scripting Language'}, {'pcaxis', 'PC-Axis'}, {'pcaxis', 'PC-Axis'}, {'peoplecode', 'PeopleCode'}, ...
                {'peoplecode', 'PeopleCode'}, {'perl', 'Perl'}, {'perl', 'Perl'}, {'perl', 'Perl'}, {'php', 'PHP'}, {'phpdoc', 'PHPDoc'}, {'php-extras', 'PHP Extras'}, {'plant-uml', 'PlantUML'}, {'plant-uml', 'PlantUML'}, ...
                {'plant-uml', 'PlantUML'}, {'plsql', 'PL/SQL'}, {'powerquery', 'PowerQuery'}, {'powerquery', 'PowerQuery'}, {'powerquery', 'PowerQuery'}, {'powershell', 'PowerShell'}, {'powershell', 'PowerShell'}, {'powershell', 'PowerShell'}, ...
                {'processing', 'Processing'}, {'processing', 'Processing'}, {'prolog', 'Prolog'}, {'promql', 'PromQL'}, {'properties', '.properties'}, {'protobuf', 'Protocol Buffers'}, {'protobuf', 'Protocol Buffers'}, {'pug', 'Pug'}, ...
                {'puppet', 'Puppet'}, {'puppet', 'Puppet'}, {'pure', 'Pure'}, {'purebasic', 'PureBasic'}, {'purebasic', 'PureBasic'}, {'purebasic', 'PureBasic'}, {'purescript', 'PureScript'}, {'purescript', 'PureScript'}, ...
                {'python', 'Python'}, {'python', 'Python'}, {'qsharp', 'Q#'}, {'qsharp', 'Q#'}, {'q', 'Q (kdb+ database)'}, {'qml', 'QML'}, {'qore', 'Qore'}, {'r', 'R'}, {'racket', 'Racket'}, {'racket', 'Racket'}, ...
                {'cshtml', 'Razor C#'}, {'cshtml', 'Razor C#'}, {'jsx', 'React JSX'}, {'tsx', 'React TSX'}, {'reason', 'Reason'}, {'reason', 'Reason'}, {'regex', 'Regex'}, {'rego', 'Rego'}, {'renpy', 'Ren\py'}, {'renpy', 'Ren\py'}, ...
                {'rescript', 'ReScript'}, {'rescript', 'ReScript'}, {'rest', 'reST (reStructuredText)'}, {'rest', 'reST (reStructuredText)'}, {'rip', 'Rip'}, {'roboconf', 'Roboconf'}, {'robotframework', 'Robot Framework'}, {'robotframework', 'Robot Framework'}, ...
                {'ruby', 'Ruby'}, {'ruby', 'Ruby'}, {'rust', 'Rust'}, {'rust', 'Rust'}, {'sas', 'SAS'}, {'sass', 'Sass (Sass)'}, {'scss', 'Sass (SCSS)'}, {'scala', 'Scala'}, {'scheme', 'Scheme'}, {'scheme', 'Scheme'}, ...
                {'shell-session', 'Shell session'}, {'shell-session', 'Shell session'}, {'shell-session', 'Shell session'}, {'smali', 'Smali'}, {'smalltalk', 'Smalltalk'}, {'smalltalk', 'Smalltalk'}, ...
                {'smarty', 'Smarty'}, {'sml', 'SML'}, {'sml', 'SML'}, {'solidity', 'Solidity (Ethereum)'}, {'solidity', 'Solidity (Ethereum)'}, {'solution-file', 'Solution file'}, {'solution-file', 'Solution file'}, {'soy', 'Soy (Closure Template)'}, ...
                {'sparql', 'SPARQL'}, {'sparql', 'SPARQL'}, {'splunk-spl', 'Splunk SPL'}, {'sqf', 'SQF: Status Quo Function (Arma 3)'}, {'sql', 'SQL'}, {'squirrel', 'Squirrel'}, {'squirrel', 'Squirrel'}, {'stan', 'Stan'}, ...
                {'stata', 'Stata Ado'}, {'stata', 'Stata Ado'}, {'iecst', 'Structured Text (IEC 61131-3)'}, {'stylus', 'Stylus'}, {'stylus', 'Stylus'}, {'supercollider', 'SuperCollider'}, {'supercollider', 'SuperCollider'}, ...
                {'swift', 'Swift'}, {'systemd', 'Systemd configuration file'}, {'t4-templating', 'T4 templating'}, {'t4-cs', 'T4 Text Templates (C#)'}, {'t4-cs', 'T4 Text Templates (C#)'}, {'t4-vb', 'T4 Text Templates (VB)'}, {'tap', 'TAP'}, {'tcl', 'Tcl'}, ...
                {'tt2', 'Template Toolkit 2'}, {'textile', 'Textile'}, {'toml', 'TOML'}, {'tremor', 'Tremor'}, {'tremor', 'Tremor'}, {'tremor', 'Tremor'}, {'turtle', 'Turtle'}, {'turtle', 'Turtle'}, ...
                {'twig', 'Twig'}, {'typescript', 'TypeScript'}, {'typescript', 'TypeScript'}, {'typoscript', 'TypoScript'}, {'typoscript', 'TypoScript'}, {'unrealscript', 'UnrealScript'}, {'unrealscript', 'UnrealScript'}, {'unrealscript', 'UnrealScript'}, ...
                {'uorazor', 'UO Razor Script'}, {'uri', 'URI'}, {'uri', 'URI'}, {'v', 'V'}, {'vala', 'Vala'}, {'vbnet', 'VB.Net'}, {'velocity', 'Velocity'}, {'velocity', 'Velocity'}, {'verilog', 'Verilog'}, {'verilog', 'Verilog'}, {'verilog', 'Verilog'}, ...
                {'vhdl', 'VHDL'}, {'vhdl', 'VHDL'}, {'vim', 'vim'}, {'visual-basic', 'Visual Basic'}, {'visual-basic', 'Visual Basic'}, {'visual-basic', 'Visual Basic'}, {'warpscript', 'WarpScript'}, {'wasm', 'WebAssembly'}, {'wasm', 'WebAssembly'}, ...
                {'web-idl', 'Web IDL'}, {'web-idl', 'Web IDL'}, {'wgsl', 'WGSL'}, {'wiki', 'Wiki markup'}, {'wolfram', 'Wolfram language'}, {'wolfram', 'Wolfram language'}, {'wolfram', 'Wolfram language'}, {'wolfram', 'Wolfram language'}, {'wren', 'Wren'}, ...
                {'xeora', 'Xeora'}, {'xeora', 'Xeora'}, {'xml-doc', 'XML doc (.net)'}, {'xojo', 'Xojo (REALbasic)'}, {'xquery', 'XQuery'}, {'xquery', 'XQuery'}, {'yaml', 'YAML'}, {'yaml', 'YAML'}, {'yang', 'YANG'}, {'zig', 'Zig'} ...
            } ...
        );
    end

    % Lookup extension in database
    if isKey(mapDatabase, ext)
        res = mapDatabase(ext);
        alias = res{1};
        langName = res{2};
    else
        % Fallback for unknown extensions
        alias = 'txt';
        langName = 'Plain Text';
    end
end
